# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2023-07-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(max_length=20)),
                ('call_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
