# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2023-07-09 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0002_buttoncall_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoncall',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
