# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2023-07-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0003_auto_20230709_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoncall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
